### ISSUE TITLE
32 bit tiff support

### ISSUE THREAD

**Issue by maxogden** [image-js/tiff-js#3]
I tried to use this on a tiff that a neuroscientist gave me and got an unsupport bit depth error. I believe it's because my tiff is 32-bit. Would this be easy to implement?

**Comment by maxogden** [comment]
I opened a PR here https://github.com/image-js/tiff-js/pull/4

**Comment by lpatiny** [comment]
:+1: we didn't have a need for it yet but it is a good improvement !

**Comment by targos** [comment]
Greyscale float32 is now supported with v1.1.0, thanks!

**Comment by maxogden** [comment]
woot, thanks!
